version: '3.8'

services:
  db:
    image: postgres:15
    container_name: job_rs_pg_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: job_rs_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: job_rs_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/job_rs_db
      SERPAPI_KEY: ${SERPAPI_KEY}
    depends_on:
      - db

volumes:
  pgdata:
